modLoader="javafml"
loaderVersion="[33,)"
license="All rights reserved"
<<<<<<< HEAD
[[mods]]
modId="${modId}"
version="${version}"
displayName="${modDisplayName}"
logoFile="logo.png"
credits="${credits}"
authors="${author}"
=======
# A URL to refer people to when problems occur with this mod
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional
# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory
# The modid of the mod
modId="${modId}" #mandatory
# The version number of the mod - there's a few well known ${} variables useable here or just hardcode it
#  will substitute the value of the Implementation-Version as read from the mod's JAR file metadata
# see the associated build.gradle script for how to populate this completely automatically during a build
version="${version}" #mandatory
 # A display name for the mod
displayName="${modDisplayName}" #mandatory
# A URL to query for updates for this mod. See the JSON update specification https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
# A URL for the "homepage" for this mod, displayed in the mod UI
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional
# A file name (in the root of the mod JAR) containing a logo for display
logoFile="logo.png" #optional
# A text field displayed in the mod UI
credits="${credits}" #optional
# A text field displayed in the mod UI
authors="${author}" #optional
# The description text for the mod (multi line!) (#mandatory)
>>>>>>> Fixed preset name not replacing properly into Mods.toml
description='''
${description}
'''
[[dependencies.${modId}]]
    modId="otg"
    mandatory=true
    versionRange="[0,)"
    ordering="BEFORE"
    side="BOTH"
