modLoader="javafml"
loaderVersion="[33,)"
license="All rights reserved"
[[mods]]
modId="${modId}"
version="${version}"
displayName="${modDisplayName}"
logoFile="logo.png"
credits="${credits}"
authors="${author}"
description='''
${description}
'''
[[dependencies.${modId}]]
    modId="otg"
    mandatory=true
    ordering="BEFORE"
    side="BOTH"